In [4]:
import numpy as np
x = np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
import numpy as np
x = np.zeros((3,4))
for i in range(3):
    for j in range(4):
        print(x[i][j], end=' ')
#수정필요

0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 

In [9]:
import numpy as np
x =[[22,3,4],[2,2,3]]
np.sum(x)

36

In [11]:
import numpy as np
x =[[22,3,4],[2,2,3]]
type(x)
# x.sum()   # 에러발생 => AttributeError: 'list' object has no attribute 'sum'
# 리스트는 sum을 못한다.
np.array(x).sum()  # 이런식으로 바꿔서 사용가능

36

In [12]:
import numpy as np
x =[[22,3,4],[2,2,3]]
np.sum(x[1])

7

In [22]:
# 인공신경망(인공지능)은 x값*w값의 합산이 y값과 최대한 차이가 나지않게하는 w값 찾기
import numpy as np
# 1번사람[x1,x2,x3],
# 2번사람[x1,x2,x3] x1을 몸무게, x2를 나이, x3를 수명량이라고 가정
x = np.array([[22,3,4],[2,2,3]])
y = np.array([100, 150])    # 1번사람의 혈압이 100, 2번사람의 혈압이 150일때 
w = np.array([3, 5, 8] )    # x1의 w값 3 / x2의 w값 5 /x3의 w값 8

x*w                         # ([22*3,3*5, 4*8 ],[2*3,2*5,3*8])


array([[66, 15, 32],
       [ 6, 10, 24]])

In [53]:
# 인공신경망(인공지능)은 x값*w값의 합산이 y값과 최대한 차이가 나지않게하는 w값 찾기
import numpy as np
# 1번사람[x1,x2,x3],
# 2번사람[x1,x2,x3] x1을 몸무게, x2를 나이, x3를 수명량이라고 가정
x = np.array([[22,3,4],[2,2,3]])
y = np.array([100, 150])   # 1번사람의 혈압이 100, 2번사람의 혈압이 150일때 
w = np.array([3, 5, 8] )   # x1의 w값 3 / x2의 w값 5 /x3의 w값 8

# x*w                        #([22*3,3*5, 4*8 ],[2*3,2*5,3*8])
y1 = x*w
y_hat=[]
for i in y1:
   y_hat.append(i.sum())
print(y_hat)
print(type(y_hat))
y_hat-y  # 하나의 셋이 array구조이면 array 구조로 포함이 되어서 연산되어 나온다./ y_hat은 list, y는 array


[113, 40]
<class 'list'>


array([  13, -110])

In [40]:
### Na : 입력되지 않은 값 /numpy 구조에서 치명적

In [39]:
## 책 확인(페이지)
# 467 람다
# 555
# 570 ~ 583 이터레이터 + 압축기법 

In [41]:
# 이터레이터 : for문을 통해 순회가능
a=[1,2,3]
for x in a:
    pass

### for Comprehension(컴프리핸션)

In [42]:
# for 컴프리핸션 - 방법1
number = [x for x in range(10)]
number



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
# for 컴프리핸션 - 방법2
# 방법1, 방법2 같음
number=[]
for x in range(10):
    number.append(x)
number

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
# 인공신경망(인공지능)은 x값*w값의 합산이 y값과 최대한 차이가 나지않게하는 w값 찾기
# for 컴프리핸션 사용
import numpy as np
# 1번사람[x1,x2,x3],
# 2번사람[x1,x2,x3] x1을 몸무게, x2를 나이, x3를 수명량이라고 가정
x = np.array([[22,3,4],[2,2,3]])
y = np.array([100, 150])   # 1번사람의 혈압이 100, 2번사람의 혈압이 150일때 
w = np.array([3, 5, 8] )   # x1의 w값 3 / x2의 w값 5 /x3의 w값 8

x*w                        #([22*3,3*5, 4*8 ],[2*3,2*5,3*8])
y1 = x*w
y_hat=[i.sum() for i in y1]
print(y_hat)

[113, 40]


## 정리
###### - glob와 os.listdir 로 폴더내의 자료를 리스트화 할 수 있다.
###### - numpy모듈을 이용하여 배열간 연산이 가능하다.
###### - PIL 모듈을 이용하여 이미지관련 연산을 할 수 있다.
######     (배열로 안바꿔도 됨. 배열자료라는 것만 인지하고 PIL모듈 기능중 필요한 기능만 사용할 수 있으면 됨)
###### - 리스트는 빈리스트 만들고 append하는 과정을 압축하여 표현할 수 있다.

### 이중 for 리스트 append